// Code generated by "stringer -type=JobBackendType"; DO NOT EDIT.

package async

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KafkaBackendJob-1]
}

const _JobBackendType_name = "KafkaBackendJob"

var _JobBackendType_index = [...]uint8{0, 15}

func (i JobBackendType) String() string {
	i -= 1
	if i < 0 || i >= JobBackendType(len(_JobBackendType_index)-1) {
		return "JobBackendType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _JobBackendType_name[_JobBackendType_index[i]:_JobBackendType_index[i+1]]
}
